test: Add simple unit test for simple commit
This first change includes a testing framework via a submodule:
shunit2[1]. It also includes a test commit message that includes only
the scope, and description, along with a new test-suite, which has a
single test to ensure that test commit message is acceptable.

[1]: https://github.com/kward/shunit2

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -1,15 +1,21 @@
 #!/bin/bash
 
-# Regex to validate the type pattern
-REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
+main() {
+	# Regex to validate the type pattern
+	REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
 
-FILE=`cat $1` # File containing the commit message
+	FILE=`cat $1` # File containing the commit message
 
-echo "Commit Message: ${FILE}"
+	echo "Commit Message: ${FILE}"
 
-if ! [[ $FILE =~ $REGEX ]]; then
-	echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
-	exit 1
-else
-	echo >&2 "Valid commit message."
+	if ! [[ $FILE =~ $REGEX ]]; then
+		echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
+		exit 1
+	else
+		echo >&2 "Valid commit message."
+	fi
+}
+
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    main $1
 fi
